# Generated by Django 5.2.5 on 2025-09-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0021_brand_image_url_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading: paste image URL', null=True),
        ),
    ]
