# Generated by Django 5.2.5 on 2025-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0022_alter_brand_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show in homepage slider'),
        ),
        migrations.AddField(
            model_name='editedapiproduct',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text='Show in homepage slider'),
        ),
    ]
