# Generated by Django 5.2.5 on 2025-09-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0023_customproduct_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='bestseller_order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Order in bestseller slider (0 = not shown)', null=True),
        ),
        migrations.AddField(
            model_name='editedapiproduct',
            name='bestseller_order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Order in bestseller slider (0 = not shown)', null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
        migrations.AlterField(
            model_name='editedapiproduct',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Bestseller'),
        ),
    ]
