# Generated by Django 5.2.5 on 2025-09-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0026_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='online_name',
            field=models.CharField(blank=True, help_text='Name displayed to customers online', max_length=100, null=True),
        ),
    ]
