# Generated by Django 5.2.5 on 2025-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0029_delete_categorywithcache_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_types',
            field=models.TextField(blank=True, help_text='Comma-separated product-type strings that belong to this category'),
        ),
    ]
